window.QUIZ_DATA = {
  title: "Álbum Interativo ECA Digital",
  screens: {
    home: "assets/album-1/home.png",
  },
  intro: {
    paragraphs: [
      "Bem-vindo(a) ao Álbum **1** da **Coleção Álbum Interativo ECA Digital!**",
      "Sua missão é descobrir como o ECA Digital ajuda você, criança ou adolescente, a se proteger na internet.",
      "Aqui, você aprenderá seus direitos e deveres no mundo digital.",
      "Responda às perguntas e revele cada figurinha para avançar na sua jornada.",
      "Conquiste troféus, complete desafios e descubra novas figurinhas pelo caminho.",
      "Para conquistar todas as figurinhas, todos os troféus e se tornar um verdadeiro Guardião(ã) Digital, você também precisará completar os Álbuns 2 e 3.",
      "Cada troféu traz um **número** ou uma **letra**, que formam um código secreto. Ao final desse álbum **\"1\"**, está explicado o que esse código oferece.",
      "🌟 Sua aventura começa agora!",
    ],
  },
  trophies: [
    {
      afterQuestion: 3,
      background: "assets/album-1/trofeu-1/fundo.png",
      image: "assets/album-1/trofeu-1/trofeu.png",
      text: "Primeira letra do código secreto\n\"**S**\" anote!",
      imageStyle: { top: 0, left: 28, width: 300 },
      textStyle: {
        top: 440,
        left: 0,
        right: 0,
        padding: "11px 20px",
        color: "#222",
        background: "#fff",
        fontSize: 18,
        lineHeight: "1.15",
      },
      nextButton: { y: 90 },
    },
  ],
  questions: [
    {
      question: "Quando um aplicativo ou jogo precisa proteger crianças?",
      screens: {},
      theme: {
        background: "assets/album-1/geral/fundo.png",
        character: "assets/album-1/geral/enki.png",
        characterStyle: { top: 70, right: 0, width: 128 },
        speech:
          "Oi, meu nome é **[[white:ENKI]]** e vou ajudar você nessa aventura, vamos começar!",
        speechStyle: { top: 69, left: 21, width: 222, fontSize: "13.5px" },
        copyStyle: { top: 153, left: 20, right: 19 },
        nextButton: { y: 90 },
        paragraphs: [
          "A lei **protege crianças e adolescentes** em jogos, \naplicativos e sites.",
          "",
          "Se um serviço digital é feito para esse público ou **pode ser acessado** facilmente **por eles**, devem ser adotadas medidas de proteção, mesmo que a empresa seja de outro país.",
        ],
      },
      questionScreen: {
        background: "assets/album-1/geral/fundo.png",
        character: "assets/album-1/pergunta-1/inanna.png",
        characterStyle: { top: 70, left: 10, width: 240 },
        speech:
          "Oi, meu nome é [[white:Inanna]] acerte a resposta e abra a **1ª figurinha**",
        speechStyle: { top: 140, left: 151, width: 195, fontSize: "13.5px" },
        bannerStyle: { top: 323, left: 43, width: 282 },
        answerCards: [
          { top: 423, left: 20, width: 90 },
          { top: 423, left: 135, width: 90 },
          { top: 423, left: 250, width: 90 },
        ],
      },
      wrongScreen: {
        background: "assets/album-1/geral/fundo.png",
        character: "assets/album-1/pergunta-1/inanna-resposta-errada.png",
        characterStyle: { top: 10, left: 60, width: 400 },
        speech: "Leia com atenção",
        speechStyle: { top: 64, left: 100, width: 115, fontSize: 18 },
        questionStyle: { top: 300, left: 13, width: 219 },
        answerStyle: { top: 380, left: 75, width: 140 },
        backControlStyle: { top: 430, left: 74 },
      },
      correctScreen: {
        background: "assets/album-1/geral/fundo-figurinha.png",
        header: "assets/album-1/geral/header-figurinha.png",
        sticker: "assets/album-1/pergunta-1/figurinha.png",
        title: "FIGURINHA (Nº 01)",
        headerStyle: { top: 7, left: 86, width: 188 },
        titleStyle: { top: 121, left: 88, width: 184 },
        stickerStyle: { top: 153, left: 78, width: 206 },
        nextButton: { y: 90 },
      },
      stickerFullScreen: {
        background: "assets/album-1/geral/fundo.png",
        sticker: "assets/album-1/pergunta-1/figurinha.png",
        stickerStyle: { top: -10, left: -24, width: 398, maxHeight: 580 },
      },
      answers: [
        {
          letter: "A",
          text: "Quando o app só funciona à noite.",
          correct: false,
        },
        {
          letter: "B",
          text: "Só quando o celular está sem internet.",
          correct: false,
        },
        {
          letter: "C",
          text: "Quando é feito para crianças ou pode ser usado por elas.",
          correct: true,
        },
      ],
    },
    {
      sectionTitle: "ECA DIGITAL - seção - 02",
      question:
        "O que os pais ou responsáveis devem fazer quando seus jovens usam a internet?",
      screens: {},
      theme: {
        background: "assets/album-1/geral/fundo.png",
        character: "assets/album-1/geral/enki.png",
        characterStyle: { top: 26, right: -10, width: 190 },
        copyStyle: {
          top: 175,
          left: 8,
          right: 7,
          padding: 8,
          background: "rgba(247, 250, 255, 0.9)",
          fontSize: 20,
          lineHeight: "1.16",
        },
        wrapAvoidStyle: { width: 100, height: 60, marginLeft: 8 },
        nextButton: { y: 90 },
        paragraphs: [
          "Crianças e adolescentes têm o direito de receber orientação e acompanhamento de seus pais ou responsáveis quando estão usando a internet.",
          "Os pais ou responsáveis têm o dever de **ajudar, proteger e acompanhar** seus filhos para que usem a internet de forma segura.",
        ],
      },
      questionScreen: {
        background: "assets/album-1/geral/fundo.png",
        character: "assets/album-1/pergunta-2/enlil.png",
        characterStyle: { top: 80, left: 160, width: 210 },
        speechClass: "tail-right",
        speech:
          "Oi, meu nome é [[white:Enlil]] acerte a resposta e abra a **2ª figurinha**",
        speechStyle: { top: 136, left: 19, width: 216, fontSize: 14 },
        bannerStyle: { top: 290, left: 37, width: 281, fontSize: 17 },
        answerCards: [
          { top: 424, left: 13, width: 100 },
          { top: 424, left: 126, width: 100 },
          { top: 424, left: 237, width: 100 },
        ],
      },
      wrongScreen: {
        background: "assets/album-1/geral/fundo.png",
        character: "assets/album-1/pergunta-2/enlil-resposta-errada.png",
        characterStyle: { top: 50, left: 140, width: 250 },
        speech: "Tente novamente",
        speechStyle: { top: 80, left: 50, width: 150, fontSize: 19 },
        question:
          "O que os pais ou responsáveis devem fazer no uso da internet por crianças e adolescentes?",
        questionStyle: { top: 250, left: 14, width: 223, fontSize: 13 },
        answerStyle: { top: 340, left: 70, width: 135 },
        backControlStyle: { top: 400, left: 75 },
      },
      correctScreen: {
        background: "assets/album-1/geral/fundo-figurinha.png",
        header: "assets/album-1/geral/header-figurinha.png",
        sticker: "assets/album-1/pergunta-2/figurinha.png",
        title: "FIGURINHA (Nº 02)",
        headerStyle: { top: 8, left: 86, width: 188 },
        titleStyle: { top: 121, left: 87, width: 186 },
        stickerStyle: { top: 151, left: 78, width: 207 },
        nextButton: { y: 90 },
      },
      stickerFullScreen: {
        background: "assets/album-1/geral/fundo.png",
        sticker: "assets/album-1/pergunta-2/figurinha.png",
        stickerStyle: { top: 0, left: -7, width: 374, maxHeight: 560 },
      },
      answers: [
        {
          letter: "A",
          text: "Não se importar com o uso do celular.",
          correct: false,
        },
        {
          letter: "B",
          text: "Ajudar, proteger e acompanhar.",
          correct: true,
        },
        {
          letter: "C",
          text: "Deixar que elas aprendam sobre os riscos digitais sem supervisão.",
          correct: false,
        },
      ],
    },
    {
      sectionTitle: "ECA DIGITAL - seção - 03",
      question:
        "O que a tecnologia deve garantir além da proteção para todas as crianças e adolescentes no digital?",
      screens: {},
      theme: {
        background: "assets/album-1/pergunta-3/fundo.png",
        character: "assets/album-1/pergunta-3/enki.png",
        characterStyle: { top: 90, left: -20, width: 200 },
        speech:
          "Agora que você já conseguiu 2 figurinhas vamos abrir mais uma para ganhar seu primeiro troféu",
        speechClass: "tail-right",
        speechStyle: {
          top: 63,
          left: 130,
          width: 205,
          fontSize: 16,
          lineHeight: "1.12",
          "--speech-bg": "#f59b74",
        },
        copyStyle: {
          top: 212,
          left: 83,
          right: 14,
          padding: 0,
          background: "transparent",
          color: "#2b2385",
          fontSize: 18,
          lineHeight: "1.15",
        },
        wrapAvoidStyle: { side: "left", width: 70, height: 150, marginRight: 8 },
        nextButton: { y: 90 },
        paragraphs: [
          "O uso da tecnologia por crianças e adolescentes deve garantir proteção, **inclusão e respeito às diferenças**, além de ajudar no crescimento emocional, social e intelectual. Também deve incentivar a educação digital e explicar de forma clara como os dados pessoais são usados.",
        ],
      },
      questionScreen: {
        background: "assets/album-1/pergunta-3/fundo.png",
        character: "assets/album-1/pergunta-3/personagem.png",
        characterStyle: { top: 75, left: -20, width: 226 },
        speech:
          "[[white:Oi, estou muito feliz só de pensar que você vai conseguir seu primeiro troféu.]]",
        speechClass: "tail-left",
        speechStyle: {
          top: 70,
          left: 144,
          width: 178,
          fontSize: 16,
          lineHeight: "1.13",
        },
        bannerStyle: {
          top: 300,
          left: 35,
          width: 280,
          color: "#282184",
          background: "#f49c75",
          fontSize: 13,
          lineHeight: "1.08",
        },
        answerClass: "gold-answer",
        answerCards: [
          { top: 426, left: 13, width: 102 },
          { top: 426, left: 123, width: 102 },
          { top: 426, left: 237, width: 102 },
        ],
      },
      wrongScreen: {
        background: "assets/album-1/pergunta-3/fundo.png",
        character: "assets/album-1/pergunta-3/personagem-resposta-errada.png",
        characterStyle: { top: 50, left: -35, width: 300 },
        speech: "Leia com atenção",
        speechStyle: {
          top: 102,
          left: 180,
          width: 130,
          fontSize: 20,
          "--speech-bg": "#ffffff",
        },
        speechClass: "tail-left",
        question:
          "O que a tecnologia deve garantir além da proteção para todas as crianças e adolescentes no digital?",
        questionStyle: {
          top: 220,
          left: 190,
          width: 144,
          color: "#282184",
          background: "#f49c75",
          fontSize: 13,
        },
        answerStyle: { top: 380, left: 190, width: 130 },
        backControlStyle: { top: 445, left: 190 },
      },
      correctScreen: {
        background: "assets/album-1/pergunta-3/fundo.png",
        header: "assets/album-1/geral/header-figurinha.png",
        sticker: "assets/album-1/pergunta-3/figurinha.png",
        title: "FIGURINHA (Nº 03)",
        headerStyle: { top: 8, left: 86, width: 188 },
        titleStyle: { top: 121, left: 87, width: 186 },
        stickerStyle: { top: 151, left: 76, width: 208 },
        nextButton: { y: 90 },
      },
      stickerFullScreen: {
        background: "assets/album-1/pergunta-3/fundo.png",
        sticker: "assets/album-1/pergunta-3/figurinha.png",
        stickerStyle: { top: -1, left: 0, width: 360, maxHeight: 560 },
      },
      answers: [
        {
          letter: "A",
          text: "Inclusão e respeito às diferenças.",
          correct: true,
        },
        {
          letter: "B",
          text: "Separar algumas pessoas como usuários menos importantes.",
          correct: false,
        },
        {
          letter: "C",
          text: "Excluir quem pensa ou age diferente.",
          correct: false,
        },
      ],
    },
    {
      sectionTitle: "ECA DIGITAL - seção - 04",
      question:
        "Como deve ser a segurança dos jovens no ambiente digital",
      screens: {},
      theme: {
        background: "assets/album-1/pergunta-4/fundo.png",
        character: "assets/album-1/pergunta-4/enki.png",
        characterStyle: { top:-42, left: 36, width: 278 },
        copyStyle: {
          top: 214,
          left: 10,
          right: 11,
          padding: 0,
          background: "transparent",
          color: "#2d277d",
          fontSize: 17.5,
          lineHeight: "1.1",
          fontWeight: "400",
        },
        nextButton: { y: 90 },
        paragraphs: [
          "Sites e apps devem ser seguros **desde o começo**, bloqueando violência, drogas, apostas e contatos perigosos. Se algo der errado, eles são obrigados a oferecer **ajuda de verdade** e educação.Lembre-se: sua segurança é um **trabalho em equipe** entre as empresas, sua família e as autoridades",
        ],
      },
      questionScreen: {
        background: "assets/album-1/pergunta-4/fundo.png",
        character: "assets/album-1/pergunta-4/ananna.png",
        characterStyle: { top: 105, left: 10, width: 298 },
        speech:
          "Vamos continuar nossa aventura.",
        speechStyle: {
          top: 109,
          left: 210,
          width: 110,
          fontSize: 16,
          lineHeight: "1.15",
        },
        bannerStyle: { top: 303, left: 39, width: 281, fontSize: 15 },
        answerCards: [
          { top: 403, left: 29, width: 135 },
          { top: 403, left: 191, width: 135 },
        ],
      },
      wrongScreen: {
        background: "assets/album-1/pergunta-4/fundo.png",
        character: "assets/album-1/pergunta-4/ananna resposta errada.png",
        characterStyle: { top: 65, left: -55, width: 285 },
        speech: "Essa precisa de atenção, Tente novamente",
        speechClass: "tail-left",
        speechStyle: {
          top: 68,
          left: 171,
          width: 122,
          fontSize: 13,
          lineHeight: "1.05",
        },
        questionStyle: {
          top: 259,
          left: 181,
          width: 133,
          background: "#2118bb",
          fontSize: 12,
        },
        answerStyle: { top: 348, left: 169, width: 112 },
        backControlStyle: { top: 420, left: 163 },
      },
      correctScreen: {
        background: "assets/album-1/geral/fundo-figurinha.png",
        header: "assets/album-1/geral/header-figurinha.png",
        sticker: "assets/album-1/pergunta-4/figurinha resposta certa.png",
        title: "FIGURINHA (Nº 04)",
        headerStyle: { top: 8, left: 86, width: 188 },
        titleStyle: { top: 112, left: 86, width: 188 },
        stickerStyle: { top: 141, left: 70, width: 220 },
        nextButton: { y: 90 },
      },
      stickerFullScreen: {
        background: "assets/album-1/pergunta-4/fundo.png",
        sticker: "assets/album-1/pergunta-4/figurinha resposta certa.png",
        stickerStyle: { top: -5, left: -22, width: 404, maxHeight: 580 },
        nextButton: { y: 90 },
      },
      demoScreen: {
        background: "assets/album-1/pergunta-4/fundo.png",
        character: "assets/album-1/pergunta-4/ananna demostração.png",
        characterStyle: { top: 113, left: -48, width: 238 },
        note: "Agora que você está entendendo a segurança digital, vamos brincar",
        noteStyle: {
          top: 66,
          left: 66,
          width: 128,
          "--note-tail-left": "18px",
          "--note-tail-bottom": "-2px",
          "--note-tail-rotate": "45deg",
        },
        board:
          "exploração, abuso sexual, violência física, intimidação, assédio, incentivo a produtos como: bebidas alcoólicas, tabaco, conteúdo pornográfico, assédio, autodiagnóstico, Bullying, automedicação, ...",
        copy:
          "As medidas razoáveis de segurança devem ser colocadas desde o começo, combatendo esses riscos para crianças e adolescentes",
        copyStyle: {
          top: 282,
          left: 115,
          width: 223,
        },
        openButton: { top: 415, left: 195 },
      },
      demoStickerScreen: {
        background: "assets/album-1/geral/fundo-figurinha.png",
        header: "assets/album-1/geral/header-figurinha.png",
        sticker: "assets/album-1/pergunta-4/figurinha demostração.png",
        title: "FIGURINHA (Nº 05)",
        headerStyle: { top: 8, left: 86, width: 188 },
        titleStyle: { top: 112, left: 86, width: 188 },
        stickerStyle: { top: 141, left: 70, width: 220 },
        nextButton: { y: 90 },
      },
      demoStickerFullScreen: {
        background: "assets/album-1/pergunta-4/fundo.png",
        sticker: "assets/album-1/pergunta-4/figurinha demostração.png",
        stickerStyle: { top: -5, left: -22, width: 404, maxHeight: 580 },
        nextButton: { y: 90 },
      },
      answers: [
        {
          letter: "A",
          text: "Quando acontecer algum problema de segurança deve ser acionada a polícia.",
          correct: false,
        },
        {
          letter: "B",
          text: "Segurança desde o começo oferecendo ajuda de verdade e trabalho em equipe.",
          correct: true,
        },
      ],
    },
  ],
};
